# This is a basic workflow to help you get started with Actions
name: Example workflow with secret input
on:
  workflow_dispatch:
    inputs:
      password:
        description: 'A secret value none should be able to read'
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
        - name: Create secret environment variable
          run: |
            SECRET_PASSWORD=$(jq -r '.inputs.password' $GITHUB_EVENT_PATH)
            echo "::add-mask::$SECRET_PASSWORD"
            # SECRET_PASSWORD can now be used without being logged
