# This is a basic workflow to help you get started with Actions

name: test input parameter with secret

on:
  workflow_call:
    secrets:
      configuration:
        type: string
        required: false
        default: ''
jobs:
  widget:
    runs-on: ubuntu-latest

    steps:
    - run: echo $CONFIGURATION
      env:
        CONFIGURATION: ${{ secrets.configuration }}
